### PR TITLE
feature: use absolute imports with package modules

### LINKED ISSUE #33: Use a canonical source for vertex.py and prompts.py
Currently, vertex.py and prompts.py are duplicated for use by the flask app. Ideally they’d instead be imported (or symlinked) from a canonical source.

### PR DESCRIPTION
**Pull request by ghost**
Closes #33 by turning the Python directories into modules and switches to use absolute imports.

-----------------

## Pull request checklist

- [x] I have linked my PR to an issue
- [x] I’ve used [conventional commits](https://github.com/FullFact/automation-docs/wiki/Conventional-commits)
- [x] My branch is up-to-date with `main`
- [x] Where appropriate, I have added or updated tests
- [x] Where appropriate, I have [updated documentation](https://github.com/FullFact/automation-docs/) to reflect my changes

### CODE REVIEW

**Comment by andylolz** [comment]
Nice. Can src/raphael_backend_flask/prompts.py be removed as part of this PR? I guess it’s no longer used.

Also: vertex.py still exists in two places, i.e. we don’t have a canonical version of that file here.

**Review by dcorney — APPROVED** [review]
LGTM!

**Comment by ff-dh** [comment]
@andylolz I mean to resolve vertex.py in another PR. This was to get a foot in the door with that.

**Comment by andylolz** [comment]
> I mean to resolve vertex.py in another PR. This was to get a foot in the door with that.

^^ That’s fine – sounds good, and +1 for merging.

I’ve reopened #33, just because while this definitely fixes it partially, I think we should keep it open until we just have one copy of these files.

**Pull request merged**
